export default [
   {
   id: '1',
   tipo: 'caes',
   fotocardpet: require('../assets/src/catioro.png'),
   nomepet: "Catioro",
   sexopet: "Macho",
   idadepet: "3 anos",
   porte: "Grande",
   raca: "SRD",
   personalidade: "Brincalhão",
   descricao: "Catioro é um amigo muito brincalhão e agitado, que gosta de correr em grandes quintais e gastar sua energia! Também é muito alegre e carinhoso e adora crianças!",
   abrigo: "MEU PET MINHA VIDA",
},
{
   id: '2',
   tipo: 'caes',
   fotocardpet: require('../assets/src/catioro.png'),
   nomepet: "Snoopy",
   sexopet: "Macho",
   idadepet: "1 anos",
   porte: "Médio",
   raca: "SRD",
   personalidade: "Calmo",
   descricao: "Snoopy é um cachorro calmo e preguiçoso, adora dormir e aconchego",
   abrigo: "CASA DOS AMIGOS PETS",
},
{
   id: '3',
   tipo: 'caes',
   fotocardpet: require('../assets/src/catioro.png'),
   nomepet: "Xauxixa",
   sexopet: "Macho",
   idadepet: "1 anos",
   porte: "Médio",
   raca: "SRD",
   personalidade: "Calmo",
   descricao: "Xauxixa é um cachorro calmo e preguiçoso, adora dormir e aconchego",
   abrigo: "MEU PET MINHA VIDA",
},
{
   id: '4',
   tipo: 'gatos',
   fotocardpet: require('../assets/src/gatinea.png'),
   nomepet: "Gatinea",
   sexopet: "Fêmea",
   idadepet: "3 anos",
   porte: "Pequeno",
   raca: "SRD",
   personalidade: "Manhosa",
   descricao: "Gatínea é uma amiga dócil e manhosa, que adora um carinho e um aconchego! Também é um pouquinho preguiçosa e adora ficar dormindo, principalmente quando está deitada perto de seus novos amigos!",
   abrigo: "CASA DOS AMIGOS PETS",
  },
  {
   id: '5',
   tipo: 'gatos',
   fotocardpet: require('../assets/src/gatinea.png'),
   nomepet: "Mingau",
   sexopet: "Macho",
   idadepet: "5 anos",
   porte: "Pequeno",
   raca: "SRD",
   personalidade: "Curioso",
   descricao: "Mingau é um gato curioso que adora descobrir cantos novos pela casa e ficar aninhado neles.",
   abrigo: "MEU PET MINHA VIDA",
  },
{
   id: '6',
   tipo: 'outros',
   fotocardpet: require('../assets/src/cacti.png'),
   nomepet: "Cacti",
   sexopet: "Macho",
   idadepet: "1 anos",
   porte: "não definido",
   raca: "Cacatua",
   personalidade: "Falador",
   descricao: "Cacti é uma cacatua alegre, divertida e curiosa! E adora comer!",
   abrigo: "MEU PET MINHA VIDA",
},
];
