export default [
   {
   id: '1',
   tipo: 'caes',
   fotocardpet: "https://m.media-amazon.com/images/I/81glJSbNU5L.png",
   nomepet: "Catioro",
   sexopet: "Macho",
   idadepet: "3 anos",
   porte: "Grande",
   raca: "SRD",
   personalidade: "Brincalhão",
   descricao: "Catioro é um amigo muito brincalhão e agitado, que gosta de correr em grandes quintais e gastar sua energia! Também é muito alegre e carinhoso e adora crianças!",
   abrigo: "MEU PET MINHA VIDA",
},
{
   id: '2',
   tipo: 'caes',
   fotocardpet: "https://i.pinimg.com/736x/35/17/d4/3517d449cd8899c313434b8336688838--cat-breeds-samoyed-dogs.jpg",
   nomepet: "Snoopy",
   sexopet: "Macho",
   idadepet: "1 anos",
   porte: "Médio",
   raca: "SRD",
   personalidade: "Calmo",
   descricao: "Snoopy é um cachorro calmo e preguiçoso, adora dormir e aconchego",
   abrigo: "CASA DOS AMIGOS PETS",
},
{
   id: '3',
   tipo: 'caes',
   fotocardpet: "https://m.media-amazon.com/images/I/81NGXVSGWFL.png",
   nomepet: "Xauxixa",
   sexopet: "Macho",
   idadepet: "1 anos",
   porte: "Médio",
   raca: "SRD",
   personalidade: "Calmo",
   descricao: "Xauxixa é um cachorro calmo e preguiçoso, adora dormir e aconchego",
   abrigo: "MEU PET MINHA VIDA",
},
{
   id: '4',
   tipo: 'gatos',
   fotocardpet: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4JEaVx8sKT0c5_CMYou_1kc0blzweRQU7tg&usqp=CAU",
   nomepet: "Gatinea",
   sexopet: "Fêmea",
   idadepet: "3 anos",
   porte: "Pequeno",
   raca: "SRD",
   personalidade: "Manhosa",
   descricao: "Gatínea é uma amiga dócil e manhosa, que adora um carinho e um aconchego! Também é um pouquinho preguiçosa e adora ficar dormindo, principalmente quando está deitada perto de seus novos amigos!",
   abrigo: "CASA DOS AMIGOS PETS",
  },
  {
   id: '5',
   tipo: 'gatos',
   fotocardpet: "https://i2.wp.com/gatinhobranco.com/wp-content/uploads/2017/03/gatos-preferem-pessoas-comida.jpg?fit=1024%2C683",
   nomepet: "Mingau",
   sexopet: "Macho",
   idadepet: "5 anos",
   porte: "Pequeno",
   raca: "SRD",
   personalidade: "Curioso",
   descricao: "Mingau é um gato curioso que adora descobrir cantos novos pela casa e ficar aninhado neles.",
   abrigo: "MEU PET MINHA VIDA",
  },
{
   id: '6',
   tipo: 'outros',
   fotocardpet: "https://www.passaro.org/wp-content/uploads/2018/10/cacatua-inca-cacatua-inca.jpg",
   nomepet: "Cacti",
   sexopet: "Macho",
   idadepet: "1 anos",
   porte: "não definido",
   raca: "Cacatua",
   personalidade: "Falador",
   descricao: "Cacti é uma cacatua alegre, divertida e curiosa! E adora comer!",
   abrigo: "MEU PET MINHA VIDA",
},
{  
   id:7,
   tipo:"Cães",
   fotocardpet:"https://play-lh.googleusercontent.com/42Bw-VZcK_OQOCa0BpFJrAK7VtNWv6dGPX4FJurmqWk6NgbYQZ_XmD8y_2Fqd_1KzGs",
   nomepet:"Scooby-Doo",
   sexopet:"Macho",
   descricao:"Ama biscoitos scooby",
   idadepet:16,
   porte:"Médio",
   raca:"Dogue Alemão",
   personalidade:"Comilão e preguiçoso"
},
{  id:8,
   tipo:"Cães",
   fotocardpet:"https://i.pinimg.com/736x/0b/f9/85/0bf98597ea553bfb9335ade825435afd.jpg",
   nomepet:"Glutão",
   sexopet:"Macho",
   idadepet:3,
   porte:"Pequeno",
   raca:"Shiba Inu",
   personalidade:"Bagunceiro"
}
];
